### ISSUE TITLE
String values are not escaped enough

### ISSUE THREAD

**Issue by seriyps** [yzh44yzh/erma#2]
```
> erma:build({select, [], "tab", [{where, [{"b", "a'b"}]}]}).
<<"SELECT * FROM tab WHERE b = 'a'b'">>
```

But I'm not sure if this escaping should be done, since it's complex task, it's highly recommended to use placeholders for arbitrary input.

**Comment by yzh44yzh** [comment]
Lib should not escape values as this work is done by database driver. No need to duplicate work. You should use placeholders in that case.
