### ISSUE TITLE
Automatic placeholders management (postprocessor)

### ISSUE THREAD

**Issue by seriyps** [yzh44yzh/erma#3]
When building complex queries, it's become realy complex task to manage placeholders numbers and parameters list, so, it will be grat to have special marks for placeholders in query tree like `{ph, RawValue}` and then use special recursive tree post-processor, which walks this tree, replace this placeholders with `"$n"` strings (or `"?"` in case of MySQL) and builds placeholder values list.

```
Query = {select, [], "tab", [{where, [{"col", {ph, RawFilter}}]}], {limit, {ph, RawLimit}}},
{Query1, Params} = erma:resolve_placeholders(Query, postgres),  % Dialect :: postgres | mysql
?assertEqual({select, [], "tab", [{where, [{"col", "$1"}]}], {limit, "$2"}}, Query1),
?assertEqual([RawFilter, RawLimit], Params)
```

**Comment by yzh44yzh** [comment]
First limited implementation is ready.
https://github.com/yzh44yzh/erma/blob/master/src/erma.erl#L61
https://github.com/yzh44yzh/erma/blob/master/test/placeholders_tests.erl#L92

Not implemented:
select ... where something IN / NOT IN (1,2,3) 
select ... where something IN subquery
placeholders for mysql

**Comment by seriyps** [comment]
:+1: thanks! Will try it bit later.

**Comment by seriyps** [comment]
I think this should be mentioned in README also.

**Comment by yzh44yzh** [comment]
of course, but when it will be ready )

**Comment by yzh44yzh** [comment]
Good enough implementation. Support placeholders for mysql and "where field in (1,2,3)".
Subqueries are still not supported.

Need to define specs for functions and update README

**Comment by yzh44yzh** [comment]
tag v1.2
