### ISSUE TITLE
Allow to use dynamic content in LIMIT

### ISSUE THREAD

**Issue by seriyps** [yzh44yzh/erma#4]
This doesn't works:

```
{select,[], "tab", [{limit,"$3"}]}
```

or even

```
Subquery = {select, ...},
{select, [], "tab", [{limit, Subquery}]}
```

or some other expression.

It's because `limit`'s values are expected to be integers.

**Comment by yzh44yzh** [comment]
I agree with placeholder there. But do you really need subquery?

**Comment by seriyps** [comment]
@yzh44yzh no, just random assumption =) Placeholder is enough for now.

**Comment by yzh44yzh** [comment]
I don't have a goal to support all possible SQL expressions, but only a reasonable subset of it )

**Comment by yzh44yzh** [comment]
placeholders are allowed for offset and limit

```
-type limit_value() :: non_neg_integer() | binary() | string().
-type limit() :: {limit, limit_value()} | {offset, limit_value(), limit, limit_value()}.

```
