### ISSUE TITLE
Backtick table name escaping is invalid for postgresql

### ISSUE THREAD

**Issue by seriyps** [yzh44yzh/erma#5]
https://github.com/yzh44yzh/erma/blob/master/src/erma_utils.erl#L48

Postgresql uses double quotes as identifier delimiter http://savage.net.au/SQL/sql-99.bnf.html#delimited%20identifier and don't accept backticks

**Comment by yzh44yzh** [comment]
Well, we have difference between postgresql and mysql. It turns out that postresql uses double quote to escape names, and mysql uses backticks. This means we need to specify database type in erma:build. 

erma:build(Query, postgres)
erma:build(Query, mysql)
erma:build(Query) % postgres by default

**Comment by seriyps** [comment]
@yzh44yzh Thanks! Yep, but this requires significant (but simple) rewrite to pass this option all around...

**Comment by yzh44yzh** [comment]
`-type erma_options() :: #{database => database()}.`

`build(Query) -> build(Query, #{database => postgresql}).`
