### ISSUE TITLE
Add support for SQL functions

### ISSUE THREAD

**Issue by seriyps** [yzh44yzh/erma#6]
It would be great to have support for SQL functions (with arguments, which may be placeholders) in different places like

`SELECT now()`
`SELECT to_char(timestamp, 'HH24:MI:SS')`
`SELECT ... FROM ... WHERE timestamp < now()`
`UPDATE ... SET updated=now()`

I guess it's enough to use `{function, Name::atom() | string(), Arguments::[atom | value()]}` and add support for it to `erma_utils:prepare_value/1`

**Comment by seriyps** [comment]
Also it looks like we need to add support for column names in `prepare_value`. Because if not, constructions like `WHERE abs(my_column) > 5` will be impossible.

**Comment by yzh44yzh** [comment]
Well, we need it )

Currently you can use "raw"
https://github.com/yzh44yzh/erma/blob/master/test/select_tests.erl#L174

but it works for "select fields" only, not for "where"
